import type { LucideIcon } from "lucide-react";

import type { Stop, FerryExclusion } from "@/types/trip-request";

import { validateStops } from "@/types/trip-request";

import { formatTime } from "@/utils/datetime-utils";

import { Flag, MapPin, Milestone } from "lucide-react";

/** Return the role name of a stop based on its position in the array. */
export function getStopRole(stops: Stop[], index: number): string {
  if (stops.length === 0) return "";
  if (index === 0) return "Start";
  if (index === stops.length - 1) return "Ziel";
  return `Stop ${index}`;
}

/** Check if an address string looks like a raw coordinate string
 *  (fallback format generated by reverseGeocode, e.g. "52.5200, 13.4050"). */
export function isRawCoordinateLabel(address: string): boolean {
  return /^-?\d+\.?\d*,\s*-?\d+\.?\d*$/.test(address.trim());
}

/** Check if an address is considered "unresolved" (empty or raw coordinates format). */
export function isUnresolvedAddress(stop: Stop): boolean {
  return (
    !stop.position || stop.address === "" || isRawCoordinateLabel(stop.address)
  );
}

/** Swap two elements in the array at the given indices. */
export function swapStops(stops: Stop[], from: number, to: number): Stop[] {
  if (
    from < 0 ||
    to < 0 ||
    from >= stops.length ||
    to >= stops.length ||
    from === to
  ) {
    return stops;
  }
  const updated = [...stops];
  // Array-Destructuring-Tausch
  const tmp = updated[from];
  updated[from] = updated[to];
  updated[to] = tmp;
  return updated;
}

/** Validate the form data (stops + SoC) and return error messages. */
export function validateForm(args: {
  stops: Stop[];
  startSoc: number;
  minArrivalSocPct: number;
  minChargingTimeMin: number;
  maxChargeSocPct?: number;
  targetSoc: number;
}): string[] {
  const errors: string[] = [];

  // Stop-spezifische Validierung (aus dem Vertrag)
  errors.push(...validateStops(args.stops));

  // SoC-Validierung
  if (
    typeof args.startSoc !== "number" ||
    isNaN(args.startSoc) ||
    args.startSoc < 0 ||
    args.startSoc > 100
  ) {
    errors.push("Start-SoC muss zwischen 0 und 100 % liegen.");
  }
  if (
    typeof args.targetSoc !== "number" ||
    isNaN(args.targetSoc) ||
    args.targetSoc < 0 ||
    args.targetSoc > 100
  ) {
    errors.push("Ziel-SoC muss zwischen 0 und 100 % liegen.");
  }
  if (
    typeof args.minChargingTimeMin !== "number" ||
    isNaN(args.minChargingTimeMin) ||
    args.minChargingTimeMin < 0 ||
    args.minChargingTimeMin > 30
  ) {
    errors.push("Min. Ladedauer muss zwischen 0 und 30 Minuten liegen.");
  }
  if (
    typeof args.minArrivalSocPct !== "number" ||
    isNaN(args.minArrivalSocPct) ||
    args.minArrivalSocPct < 0 ||
    args.minArrivalSocPct > 100
  ) {
    errors.push("Min. SoC an Ladestationen muss zwischen 0 und 100 % liegen.");
  }
  if (
    args.maxChargeSocPct !== undefined &&
    (typeof args.maxChargeSocPct !== "number" ||
      isNaN(args.maxChargeSocPct) ||
      args.maxChargeSocPct < 0 ||
      args.maxChargeSocPct > 100)
  ) {
    errors.push("Max. Lade-SoC muss zwischen 0 und 100 % liegen.");
  }

  return errors;
}

/** Compare two FerryExclusion entries for content equality. */
export function sameFerryExclusion(
  a: FerryExclusion,
  b: FerryExclusion,
): boolean {
  return (
    a.name === b.name &&
    a.bboxSw[0] === b.bboxSw[0] &&
    a.bboxSw[1] === b.bboxSw[1] &&
    a.bboxNe[0] === b.bboxNe[0] &&
    a.bboxNe[1] === b.bboxNe[1]
  );
}

/** Add or remove a ferry connection from the exclusion list. */
export function toggleFerryExclusion(
  list: FerryExclusion[],
  ferry: FerryExclusion,
  avoid: boolean,
): FerryExclusion[] {
  const alreadyExists = list.some((f) => sameFerryExclusion(f, ferry));
  if (avoid) {
    return alreadyExists ? list : [...list, ferry];
  }
  return list.filter((f) => !sameFerryExclusion(f, ferry));
}

/** Stable identity key for a ferry connection (name + bounding box),
 *  for indexing React state and lists outside of array index. */
export function ferryKey(entry: FerryExclusion): string {
  return `${entry.name}|${entry.bboxSw.join(",")}|${entry.bboxNe.join(",")}`;
}

/** Icon + background color of the timeline marker for a stop, depending
 *  on its role (start/waypoint/destination). */
export function getStopTimelineIcon(
  stops: Stop[],
  index: number,
): { Icon: LucideIcon; background: string } {
  if (index === 0) return { Icon: Flag, background: "#e0e7ff" };
  if (index === stops.length - 1) {
    return { Icon: MapPin, background: "#fef3c7" };
  }
  return { Icon: Milestone, background: "#f3f4f6" };
}

/** Check if two timestamps are distinguishable as displayed time (HH:mm).
 *  Suppresses a redundant second time badge when arrival and
 *  departure of a route entry fall on the same minute - especially
 *  for ferries whose time is estimated as a single position cluster
 *  due to no simulated "on-water" travel (see
 *  `estimatePositionTiming` in `timing-utils.ts`), where arrival and departure
 *  may therefore be identical. `null` is always considered distinguishable (the
 *  caller already decides based on `null` whether to render a badge at all). */
export function differsAsTime(a: string | null, b: string | null): boolean {
  if (a === null || b === null) return true;
  return formatTime(a) !== formatTime(b);
}

/** Prefix under which all Tesla Supercharger stations in `data/superchargers.ts`
 *  are named (e.g. "Tesla Supercharger - Berlin Alexanderplatz"). Redundant in
 *  the compact route timeline, as the charging stop's zap icon is already
 *  clearly identifiable as a charging stop. */
const SUPERCHARGER_NAME_PREFIX = "Tesla Supercharger - ";

/** Shorten a charging station's display name by removing the redundant
 *  "Tesla Supercharger - " prefix (see `SUPERCHARGER_NAME_PREFIX`). Names
 *  without this prefix (e.g. other providers) remain unchanged. */
export function formatChargingStationName(name: string): string {
  return name.startsWith(SUPERCHARGER_NAME_PREFIX)
    ? name.slice(SUPERCHARGER_NAME_PREFIX.length)
    : name;
}

/** Format a driving segment distance in km, one decimal place,
 *  German number format (comma instead of period). */
export function formatDrivingSegmentDistance(distanceKm: number): string {
  return `${distanceKm.toLocaleString("de-DE", {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  })} km`;
}

/** Format a driving segment duration in minutes as "Xh Ymin" or "Ymin"
 *  (same format as `formatChargingDuration` in `Map.tsx`). */
export function formatDrivingSegmentDuration(durationMin: number): string {
  const totalMinutes = Math.round(durationMin);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  return hours > 0 ? `${hours}h ${minutes}min` : `${minutes}min`;
}
