#!/usr/bin/env python3
"""Translate German text in src/tripplanner/ Python files to English."""
import re
from pathlib import Path

SRC = Path("src/tripplanner")

DE_TO_EN = {
    # Module docstrings
    '"""Kernlogik': '"""Core logic',
    '"""Modul': '"""Module',
    '"""Optimierungs-Modul': '"""Optimization module',
    '"""Datenmodelle': '"""Data models',
    '"""provider-Schicht': '"""Provider layer',
    '"""Routing-Anbieter': '"""Routing provider',
    '"""Simulation': '"""Simulation',
    '"""Wetter': '"""Weather',
    '"""Wind': '"""Wind',
    '"""Batterie': '"""Battery',
    '"""Energie': '"""Energy',
    '"""Höhenprofil': '"""Elevation profile',
    '"""Auflistung': '"""Listing',
    '"""Auflisten': '"""Listing',
    '"""Aufzaehlung': '"""Enumeration',
    '"""Beschreibung': '"""Description',
    '"""Bezeichnung': '"""Designation',
    '"""Beschraenkung': '"""Restriction',
    '"""Einschraenkung': '"""Restriction',
    '"""Datenquelle': '"""Data source',
    '"""Datenbank': '"""Database',
    '"""Initialisiert': '"""Initializes',
    '"""initialisiert': '"""initializes',
    '"""Initialisiere': '"""Initializes',
    '"""Verwaltet': '"""Manages',
    '"""Verwendet': '"""Uses',
    '"""Erstellt': '"""Creates',
    '"""Erstelle': '"""Creates',
    '"""Erzeugt': '"""Creates',
    '"""Ermöglicht': '"""Enables',
    '"""Ermittelt': '"""Determines',
    '"""Liefert': '"""Returns',
    '"""holt': '"""fetches',
    '"""Abruf': '"""Fetch',
    '"""Auslesen': '"""Read',
    '"""Auswerten': '"""Evaluate',
    '"""Berechnen': '"""Calculate',
    '"""Berechnung': '"""Calculation',
    '"""Berechnet': '"""Calculates',
    '"""Verbraucht': '"""Consumes',
    '"""Verbrauch': '"""Consumption',
    '"""Wartet': '"""Waits',
    '"""warten': '"""wait',
    '"""Warten': '"""Wait',
    '"""Filtert': '"""Filters',
    '"""Filter': '"""Filter',
    '"""Gibt': '"""Returns',
    '"""Zurück': '"""Back',
    '"""Zurückgegeben': '"""Returned',
    '"""Ankunft': '"""Arrival',
    '"""Abfahrt': '"""Departure',
    '"""Geschwindigkeit': '"""Speed',
    '"""Tempolimit': '"""Speed limit',
    '"""Distanz': '"""Distance',
    '"""Laenge': '"""Length',
    '"""Hoehe': '"""Height',
    '"""Höhe': '"""Height',
    '"""Steigung': '"""Gradient',
    '"""Gefälle': '"""Decline',
    '"""Anstieg': '"""Ascent',
    '"""Berg': '"""Hill',
    '"""Tal': '"""Valley',
    '"""Ebene': '"""Plain',
    '"""Lang': '"""Long',
    '"""Kurz': '"""Short',
    '"""Schnell': '"""Fast',
    '"""Langsam': '"""Slow',
    '"""Gerade': '"""Straight',
    '"""Kurve': '"""Curve',
    '"""Bogen': '"""Arc',
    '"""Wende': '"""Turn',
    '"""Abzweig': '"""Branch',
    '"""Kreuzung': '"""Intersection',
    '"""Ampel': '"""Traffic light',
    '"""Kreisverkehr': '"""Roundabout',
    '"""Maut': '"""Toll',
    '"""Stau': '"""Traffic jam',
    '"""Baustelle': '"""Construction site',
    '"""Sperre': '"""Closure',
    '"""Umleitung': '"""Detour',
    '"""Ausfahrt': '"""Exit',
    '"""Einfahrt': '"""Entrance',
    '"""Überfahrt': '"""Crossing',
    '"""Fähre': '"""Ferry',
    '"""Brücke': '"""Bridge',
    '"""Tunnel': '"""Tunnel',
    '"""Parken': '"""Parking',
    '"""Ladepunkt': '"""Charging point',
    '"""Netzwerk': '"""Network',
    '"""System': '"""System',
    '"""Prozess': '"""Process',
    '"""Hilfsfunktion': '"""Helper function',
    '"""Wrapper': '"""Wrapper',
    '"""Adapter': '"""Adapter',
    '"""Factory': '"""Factory',
    '"""Builder': '"""Builder',
    '"""Parser': '"""Parser',
    '"""Validator': '"""Validator',
    '"""Serializer': '"""Serializer',
    '"""Transformer': '"""Transformer',
    '"""Konverter': '"""Converter',
    '"""Renderer': '"""Renderer',
    '"""Exporter': '"""Exporter',
    '"""Importer': '"""Importer',
    '"""Manager': '"""Manager',
    '"""Handler': '"""Handler',
    '"""Listener': '"""Listener',
    '"""Observer': '"""Observer',
    # Common phrases
    'Kernlogik': 'Core logic',
    'für das': 'for the',
    'für den': 'for the',
    'für die': 'for the',
    'für eine': 'for a',
    'für einen': 'for a',
    'für ein': 'for a',
    'für alle': 'for all',
    'für jede': 'for each',
    'für jedes': 'for each',
    'ohne': 'without',
    'entlang': 'along',
    'innerhalb': 'within',
    'außerhalb': 'outside',
    'nach': 'after',
    'vor': 'before',
    'zwischen': 'between',
    'über': 'over',
    'unter': 'under',
    'gegenüber': 'opposite',
    'während': 'during',
    'bis': 'until',
    'seit': 'since',
    'durch': 'through',
    'wegen': 'because of',
    'trotz': 'despite',
    'mit': 'with',
    'von': 'from',
    'zu': 'to',
    'an': 'at',
    'auf': 'on',
    'in': 'in',
    'aus': 'out of',
    'bei': 'at',
    'für': 'for',
    'und': 'and',
    'oder': 'or',
    'aber': 'but',
    'wenn': 'if',
    'als': 'when',
    'damit': 'so that',
    'weil': 'because',
    'obwohl': 'although',
    'ob': 'whether',
    'solang': 'as long as',
    'solange': 'as long as',
    'sodaß': 'so that',
    'daß': 'that',
    'da': 'since',
    'weil': 'because',
    'denn': 'because',
    'jedoch': 'however',
    'sondern': 'but rather',
    'zwar': 'indeed',
    'allerdings': 'however',
    'immerhin': 'after all',
    'schließlich': 'finally',
    'z.B.': 'e.g.',
    'usw.': 'etc.',
    'bzw.': 'respectively',
    'ggf.': 'if applicable',
    'inkl.': 'including',
    'exkl.': 'excluding',
    'inklusive': 'including',
    'exklusiv': 'exclusive',
    'ausschließlich': 'exclusively',
    'einschließlich': 'including',
    'ausgeschlossen': 'excluded',
    'enthalten': 'contained',
    'beinhalten': 'contain',
    'umfassen': 'include',
    'betreffen': 'affect',
    'betrifft': 'affects',
    'Berechnung': 'calculation',
    'berechnung': 'calculation',
    'berechnet': 'calculates',
    'berechnen': 'calculate',
    'Berechnen': 'Calculate',
    'verbraucht': 'consumes',
    'Verbrauch': 'consumption',
    'verbrauch': 'consumption',
    'verwendet': 'uses',
    'Verwendet': 'Uses',
    'Verwendung': 'Use',
    'verwenden': 'use',
    'Verwenden': 'Use',
    'Verwenden': 'Use',
    'Verwenden': 'Use',
    'Wartet': 'Waits',
    'warten': 'wait',
    'Warten': 'Wait',
    'Filtert': 'Filters',
    'filtert': 'filters',
    'Filter': 'Filter',
    'Filter': 'Filter',
    'Gibt': 'Returns',
    'gibt': 'returns',
    'Zurück': 'Back',
    'zurück': 'back',
    'Zurückgegeben': 'Returned',
    'zurückgegeben': 'returned',
    'Ankunft': 'Arrival',
    'ankunft': 'arrival',
    'Abfahrt': 'Departure',
    'abfahrt': 'departure',
    'Geschwindigkeit': 'Speed',
    'geschwindigkeit': 'speed',
    'Tempolimit': 'Speed limit',
    'tempolimit': 'speed limit',
    'Distanz': 'Distance',
    'distanz': 'distance',
    'Laenge': 'Length',
    'laenge': 'length',
    'Hoehe': 'Height',
    'hoehe': 'height',
    'Höhe': 'Height',
    'höhe': 'height',
    'Steigung': 'Gradient',
    'steigung': 'gradient',
    'Gefälle': 'Decline',
    'gefaelle': 'decline',
    'Anstieg': 'Ascent',
    'anstieg': 'ascent',
    'Berg': 'Hill',
    'berg': 'hill',
    'Tal': 'Valley',
    'tal': 'valley',
    'Ebene': 'Plain',
    'ebene': 'plain',
    'Flach': 'Flat',
    'flach': 'flat',
    'Steil': 'Steep',
    'steil': 'steep',
    'Lang': 'Long',
    'lang': 'long',
    'Kurz': 'Short',
    'kurz': 'short',
    'Schnell': 'Fast',
    'schnell': 'fast',
    'Langsam': 'Slow',
    'langsam': 'slow',
    'Gerade': 'Straight',
    'gerade': 'straight',
    'Kurve': 'Curve',
    'kurve': 'curve',
    'Bogen': 'Arc',
    'bogen': 'arc',
    'Wende': 'Turn',
    'wende': 'turn',
    'Abzweig': 'Branch',
    'abzweig': 'branch',
    'Kreuzung': 'Intersection',
    'kreuzung': 'intersection',
    'Ampel': 'Traffic light',
    'ampel': 'traffic light',
    'Kreisverkehr': 'Roundabout',
    'kreisverkehr': 'roundabout',
    'Maut': 'Toll',
    'maut': 'toll',
    'Stau': 'Traffic jam',
    'stau': 'traffic jam',
    'Baustelle': 'Construction site',
    'baustelle': 'construction site',
    'Sperre': 'Closure',
    'sperre': 'closure',
    'Umleitung': 'Detour',
    'umleitung': 'detour',
    'Ausfahrt': 'Exit',
    'ausfahrt': 'exit',
    'Einfahrt': 'Entrance',
    'einfahrt': 'entrance',
    'Überfahrt': 'Crossing',
    'überfahrt': 'crossing',
    'Fähre': 'Ferry',
    'fahre': 'ferry',
    'Brücke': 'Bridge',
    'brücke': 'bridge',
    'Parken': 'Parking',
    'parken': 'parking',
    'Ladepunkt': 'Charging point',
    'ladepunkt': 'charging point',
    'Netzwerk': 'Network',
    'netzwerk': 'network',
    'System': 'System',
    'system': 'system',
    'Prozess': 'Process',
    'prozess': 'process',
    'Hilfsfunktion': 'Helper function',
    'hilfsfunktion': 'helper function',
    'Wrapper': 'Wrapper',
    'wrapper': 'wrapper',
    'Adapter': 'Adapter',
    'adapter': 'adapter',
    'Factory': 'Factory',
    'factory': 'factory',
    'Builder': 'Builder',
    'builder': 'builder',
    'Parser': 'Parser',
    'parser': 'parser',
    'Validator': 'Validator',
    'validator': 'validator',
    'Serializer': 'Serializer',
    'serializer': 'serializer',
    'Transformer': 'Transformer',
    'transformer': 'transformer',
    'Konverter': 'Converter',
    'konverter': 'converter',
    'Renderer': 'Renderer',
    'renderer': 'renderer',
    'Exporter': 'Exporter',
    'exporter': 'exporter',
    'Importer': 'Importer',
    'importer': 'importer',
    'Manager': 'Manager',
    'manager': 'manager',
    'Handler': 'Handler',
    'handler': 'handler',
    'Listener': 'Listener',
    'listener': 'listener',
    'Observer': 'Observer',
    'observer': 'observer',
    'Initialisiert': 'Initializes',
    'initialisiert': 'initializes',
    'Initialisiere': 'Initializes',
    'Verwaltet': 'Manages',
    'Verwendet': 'Uses',
    'Erstellt': 'Creates',
    'Erstelle': 'Creates',
    'Erzeugt': 'Creates',
    'Ermöglicht': 'Enables',
    'Ermittelt': 'Determines',
    'Liefert': 'Returns',
    'holt': 'fetches',
    'Abruf': 'Fetch',
    'Auslesen': 'Read',
    'Auswerten': 'Evaluate',
}

def has_german(text):
    return bool(re.search(r'[\u00e4\u00f6\u00fc\u00c4\u00d6\u00dc\u00df]', text))

def translate(text):
    result = text
    for german, english in sorted(DE_TO_EN.items(), key=len, reverse=True):
        result = result.replace(german, english)
    return result

def main():
    py_files = list(SRC.glob('**/*.py'))
    py_files = [f for f in py_files if '__pycache__' not in str(f)]
    print(f"Processing {len(py_files)} Python files...")
    modified = 0
    for path in sorted(py_files):
        original = path.read_text(encoding='utf-8')
        if not has_german(original):
            continue
        translated = translate(original)
        if translated != original:
            path.write_text(translated, encoding='utf-8')
            print(f"  Translated: {path.relative_to(Path.cwd())}")
            modified += 1
    print(f"Modified {modified} files")

if __name__ == '__main__':
    main()
